### ISSUE TITLE
Can't find collection

### ISSUE THREAD

**Issue by LiMiTLESSalpha** [k0rnh0li0/rightclicker#5]
trying to download a collection but it says that it doesn't exist, how i can fix this?

**Comment by jordanmaurice** [comment]
What collection were you downloading?  So long as you're passing it an existing collection name, it should return the appropriate results. 

https://opensea.io/collection/boredapeyachtclub 

Replaced 'boredapeyachtclub' in the URL above with the collection name you're trying to download, if you receive a 404 error that is likely why it fails to download.

**Comment by LiMiTLESSalpha** [comment]
Im trying to download this collection, I put the name from the link but it
says that the collection doesn’t exist;

https://opensea.io/collection/monkeyyellow1

Im not sure what’s the problem here as I do use the name in the link
“monkeyyellow1”.

Have u got any idea?

Thank you for the reply!

**Comment by jordanmaurice** [comment]
Your problem seems to be an issue with the OpenSea API and not this library. 

https://api.opensea.io/assets?collection=boredapeyachtclub <-- this shows the results of that other collection, notice assets in this case is not an empty array.

https://api.opensea.io/assets?collection=monkeyyellow1 <-- returns null and an empty array for assets

Interestingly, I tried about a dozen different collection names and so far only the one you shared didn't work, the rest all returned results as expected. 

I would maybe suggest trying their support team to see why this one collection does not yield any results from the API.  Here is their discord server which may be your best bet -- https://discord.com/invite/opensea

Good luck!

**Comment by Pizzanomicon** [comment]
I'm noticing this problem when using collections on the Polygon chain- I'm still early in bugtesting, but so far I can't seem to get this to work with anything listed as Polygon.  Example: https://opensea.io/collection/sprkon-b-w-collections

**Comment by Pizzanomicon** [comment]
Update:  As far as I can tell, collections using the following chains do not work:
Polygon
Optimism
Klaytn
Avalanche
Arbitrum
Solana
in fact, only the Etherium chain seems to work.  Would love to crack this!

**Comment by Pizzanomicon** [comment]
@jordanmaurice is still correct-  In chatting with OpenSea, they confirmed the API does not handle these chains.  There is a roadmap for the API to handle them in the future, but no indication of when that will be.
